"""operation type table

Revision ID: 1b0eb898d3c7
Revises: b2b352a6c856
Create Date: 2019-09-09 10:55:43.293531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0eb898d3c7'
down_revision = 'b2b352a6c856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation__type__lookup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation__type__lookup_type_name'), 'operation__type__lookup', ['type_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation__type__lookup_type_name'), table_name='operation__type__lookup')
    op.drop_table('operation__type__lookup')
    # ### end Alembic commands ###
