"""favorites table

Revision ID: 276767647d2a
Revises: 740f0e9e1de0
Create Date: 2019-09-09 10:54:05.838520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276767647d2a'
down_revision = '740f0e9e1de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=False),
    sa.Column('cteated_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories__lookup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_title'), 'favorite', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_title'), table_name='favorite')
    op.drop_table('favorite')
    # ### end Alembic commands ###
