"""remove unique on favorites

Revision ID: 2e160c4d8306
Revises: dc17005b1c59
Create Date: 2019-09-10 22:55:36.784673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e160c4d8306'
down_revision = 'dc17005b1c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_favorite_title', table_name='favorite')
    op.create_index(op.f('ix_favorite_title'), 'favorite', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_title'), table_name='favorite')
    op.create_index('ix_favorite_title', 'favorite', ['title'], unique=True)
    # ### end Alembic commands ###
