"""categories table

Revision ID: 92fea4021ea9
Revises: 276767647d2a
Create Date: 2019-09-09 10:54:37.315359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92fea4021ea9'
down_revision = '276767647d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta__data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('value', sa.String(length=30), nullable=False),
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta__data_key'), 'meta__data', ['key'], unique=False)
    op.create_index(op.f('ix_meta__data_value'), 'meta__data', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta__data_value'), table_name='meta__data')
    op.drop_index(op.f('ix_meta__data_key'), table_name='meta__data')
    op.drop_table('meta__data')
    # ### end Alembic commands ###
