"""logs table

Revision ID: 97ebe7dba213
Revises: 1b0eb898d3c7
Create Date: 2019-09-09 10:56:06.275167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ebe7dba213'
down_revision = '1b0eb898d3c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit__log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=False),
    sa.Column('item_type_id', sa.Integer(), nullable=False),
    sa.Column('operation_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_type_id'], ['item__type__lookup.id'], ),
    sa.ForeignKeyConstraint(['operation_type_id'], ['operation__type__lookup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit__log')
    # ### end Alembic commands ###
