"""item type table

Revision ID: b2b352a6c856
Revises: 92fea4021ea9
Create Date: 2019-09-09 10:55:13.542257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b352a6c856'
down_revision = '92fea4021ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item__type__lookup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item__type__lookup_type_name'), 'item__type__lookup', ['type_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item__type__lookup_type_name'), table_name='item__type__lookup')
    op.drop_table('item__type__lookup')
    # ### end Alembic commands ###
