"""normalise logs table

Revision ID: dc17005b1c59
Revises: 
Create Date: 2019-09-09 23:36:57.881143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc17005b1c59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit__log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories__lookup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('cteated_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories__lookup_title'), 'categories__lookup', ['title'], unique=True)
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=False),
    sa.Column('cteated_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories__lookup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_title'), 'favorite', ['title'], unique=True)
    op.create_table('meta__data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('value', sa.String(length=30), nullable=False),
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta__data_key'), 'meta__data', ['key'], unique=False)
    op.create_index(op.f('ix_meta__data_value'), 'meta__data', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta__data_value'), table_name='meta__data')
    op.drop_index(op.f('ix_meta__data_key'), table_name='meta__data')
    op.drop_table('meta__data')
    op.drop_index(op.f('ix_favorite_title'), table_name='favorite')
    op.drop_table('favorite')
    op.drop_index(op.f('ix_categories__lookup_title'), table_name='categories__lookup')
    op.drop_table('categories__lookup')
    op.drop_table('audit__log')
    # ### end Alembic commands ###
